### PR TITLE
feat: nested directory specific configuration

### PR DESCRIPTION
**Pull request by dsherret**
This does not implement inheritance of ancestor configs yet, but that should now be trivial to do.

Part of #711

### CODE REVIEW

**Comment by dsherret** [comment]
There is no performance difference between this and main, however between main and the last release there has been a performance regression due to my refactorings in #712.
